#![forbid(unsafe_code)]
//! Agent-native CLI for Mermaid diagrams: author, render (mmdc/HTTP), and verify diagrams.
//!
//! Generated by `cli-anything-new`. Fill in the domain logic in `domain/` and
//! `backend.rs`; the boilerplate here is part of the cli-anything-rust harness.

pub mod backend;
pub mod cli;
pub mod domain;
pub mod repl_cmds;

use std::process::ExitCode;

use clap::{CommandFactory, Parser};
use cli_anything_core::prelude::*;

use crate::cli::{Cli, Command};
use crate::domain::project::Project;

/// Software name (used for the skin, history file, and SKILL metadata).
pub const SOFTWARE: &str = "mermaid";
/// Crate version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Library entry point. Returns the process exit code.
pub fn run() -> ExitCode {
    let cli = Cli::parse();
    let skin = Skin::new(SOFTWARE, VERSION);

    // Open a project up front if one was requested.
    let mut session: Session<Project> = Session::new();
    if let Some(path) = cli.project.clone() {
        match open_project::<Project>(&path) {
            Ok(state) => session.open(state, &path),
            Err(e) => return repl_cmds::fail(&skin, cli.json, "project.open", &e),
        }
    }

    match cli.command {
        // No subcommand → interactive REPL.
        None => {
            let mut handler = repl_cmds::Repl::new(skin.clone(), session, cli.json);
            let history = cli_anything_core::skin::repl::default_history_path(SOFTWARE);
            let _ = run_repl(&skin, history.as_deref(), &mut handler);
            ExitCode::SUCCESS
        }
        // Hidden: regenerate SKILL.md from the real clap command tree.
        Some(Command::EmitSkill { output }) => {
            let md = emit_skill(&Cli::command(), &repl_cmds::skill_meta());
            match std::fs::write(&output, md) {
                Ok(()) => {
                    skin.success(&format!("wrote {}", output.display()));
                    ExitCode::SUCCESS
                }
                Err(e) => {
                    skin.error(&format!("failed to write {}: {e}", output.display()));
                    ExitCode::FAILURE
                }
            }
        }
        // One-shot command: auto-saves on success unless --dry-run.
        Some(command) => {
            let mut guard = AutoSaveGuard::new(&mut session, cli.dry_run);
            let code = repl_cmds::dispatch(command, guard.session(), &skin, cli.json);
            if code != 0 {
                guard.disarm();
                return ExitCode::FAILURE;
            }
            match guard.commit() {
                Ok(_) => ExitCode::SUCCESS,
                Err(e) => repl_cmds::fail(&skin, cli.json, "project.save", &e),
            }
        }
    }
}
